import = [
    "~/.config/alacritty/catppuccin-macchiato.toml",
]

[env]
TERM = "xterm-256color"

[window]
decorations = "None"
opacity = 0.5
startup_mode = "Windowed"

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
bold_italic = { family = "FiraCode Nerd Font", style = "Bold Italic" }
size = 14.0

